name: Push pandatouch to Espressif Component Service

on:
  push:
    tags: ['pandatouch-v*']
  pull_request:
    types: [opened, reopened, synchronize]
    paths: ['pandatouch/**', '.github/**']
  repository_dispatch:
    types: [upload-component]

jobs:
  upload_component:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: espressif/upload-components-ci-action@v2
        with:
          components: pandatouch
          namespace: "fmauneko"
          dry_run: ${{ !(github.event_name == 'repository_dispatch' || startsWith(github.ref, 'refs/tags/pandatouch-v')) || github.repository_owner != 'fmauNeko' }}
