name: Push pandatouch_noglib to Espressif Component Service

on:
  push:
    tags: ["pandatouch-v*"]
  pull_request:
    types: [opened, reopened, synchronize]
    paths: ["pandatouch/**", ".github/**"]

jobs:
  upload_noglib:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Generate pandatouch_noglib
        run: |
          pip install idf-component-manager==2.* py-markdown-table --upgrade
          python .github/ci/bsp_noglib.py pandatouch
      - uses: espressif/upload-components-ci-action@v2
        with:
          components: pandatouch_noglib
          namespace: "fmauneko"
          dry_run: ${{ !startsWith(github.ref, 'refs/tags/pandatouch-v') || github.repository_owner != 'fmauNeko' }}
          commit_sha: ""
